### ISSUE TITLE
Repository for hosting CertRemainTime

### ISSUE THREAD

**Issue by FaZeIlLuMiNaTi** [lululombard/CertRemainTime#12]
I’m currently hosting the latest deb on my repo at https://repo.dongo.pro, in case you’re interested and wanted to add that to the readme.

**Comment by lululombard** [comment]
Thanks ! Feel free to edit the README so as long as you’re not hosting pirated content on your repo.

**Comment by FaZeIlLuMiNaTi** [comment]
I'll test internally on my own repo, and use BigBoss now that Cydia is out.
