### ISSUE TITLE
Saigon not supported

### ISSUE THREAD

**Issue by lululombard** [lululombard/CertRemainTime#14]
Saigon jailbreak (10.2.1) isn't supported, and as I do no longer own a jailbroken device, I'd like for someone to add support for it.
Thanks !

**Comment by FaZeIlLuMiNaTi** [comment]
I’m working on this, I’ll create a PR soon.

**Comment by FaZeIlLuMiNaTi** [comment]
Commit https://github.com/lululombard/CertRemainTime/commit/8edbe0ccaf994259647f0c27dc1f2f201b1eebf7 closes this.
