### ISSUE TITLE
Meridian Compatibility

### ISSUE THREAD

**Issue by MrWheaties88** [lululombard/CertRemainTime#19]
Does not support Meridian jailbreak tool. States no certificate Compatibility.

**Comment by FaZeIlLuMiNaTi** [comment]
Will sort this within the next day or so.

**Comment by lululombard** [comment]
Thanks for the report, and thank you @FaZeIlLuMiNaTi you deserve your name in the app now :p

**Comment by lululombard** [comment]
Update pushed to BigBoss, should be live in 48hrs max 😄
