### ISSUE TITLE
yalu102 with Tweakbox

### ISSUE THREAD

**Issue by lululombard** [lululombard/CertRemainTime#22]
Hey, someone reported that their version of yalu102 isn't compatible with CertRemainTime.
Here's the plist cert:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AppIDName</key>
	<string>XC com ctvit ----</string>
	<key>ApplicationIdentifierPrefix</key>
	<array>
	<string>8NHBQFH69B</string>
	</array>
	<key>CreationDate</key>
	<date>2018-03-22T07:13:25Z</date>
	<key>Platform</key>
	<array>
		<string>iOS</string>
	</array>
    <key>IsXcodeManaged</key>
    <false/>
	<key>DeveloperCertificates</key>
</dict>
</plist>
```

If someone could implement this it would be great, thanks :)

**Comment by FaZeIlLuMiNaTi** [comment]
I'll add support for this certificate (probably sometime in the next 24 hours). Did they mention where they downloaded yalu102 from?

**Comment by lululombard** [comment]
Nope, got no clue where this is coming from

**Comment by lululombard** [comment]
Oh wait don't add that, it looks like it's a cert from a porn app

**Comment by FaZeIlLuMiNaTi** [comment]
Really? What makes you say that?

**Comment by lululombard** [comment]
It's coming from https://d.pear2.cc/pear1.1.1.t.ipa and it makes calls to yu83.site which very much looks like a japanese porn website

**Comment by FaZeIlLuMiNaTi** [comment]
Just checked. Same AppIDName in the ipa you just linked. That app definitely seems related to porn - it contains "18page.html", and nothing related to yalu (or any other app-based jailbreak). I guess this issue should be closed?

**Comment by lululombard** [comment]
Yup! Case closed!
