### ISSUE TITLE
Support unc0ver jailbreak

### ISSUE THREAD

**Issue by lululombard** [lululombard/CertRemainTime#23]
Hi!

the unc0ver jailbreak is not supported by CertRemainTime.

It would be great if someone can update it (wink wink @FaZeIlLuMiNaTi).

Thanks!

**Comment by FaZeIlLuMiNaTi** [comment]
I’ll do this in my spare time today. I’ll aim to push a new deb by the end of the day 🌚

**Comment by lululombard** [comment]
As fast as sanic, thx!

**Comment by FaZeIlLuMiNaTi** [comment]
Just a quick question, does the email “contact@lululombard.fr” still exist? If not, should I change it to direct users to the github issues page? Thanks.

**Comment by lululombard** [comment]
Yes it still exists, if I created that issue it's because someone sent me an email on this address :)

**Comment by FaZeIlLuMiNaTi** [comment]
Okay, great :).

**Comment by FaZeIlLuMiNaTi** [comment]
https://github.com/lululombard/CertRemainTime/pull/24 adds unc0ver support :)

**Comment by lululombard** [comment]
Thanks, submitted to BigBoss!
<img width="428" alt="image" src="https://user-images.githubusercontent.com/2182934/54289086-79ad5f80-45a0-11e9-8772-c4f9deac765b.png">
